import { NextResponse } from "next/server";
import {
  PDFDocument,
  StandardFonts,
  rgb,
  type PDFFont,
  type PDFPage,
} from "pdf-lib";

export const runtime = "nodejs";

type NoticePayload = {
  title?: string;
  companyName?: string;
  dueDate?: string;
  noticeText: string;
};

type PdfRequestBody = {
  fileName?: string;
  notices: NoticePayload[];
};

const PAGE_WIDTH = 595.28;
const PAGE_HEIGHT = 841.89;
const MARGIN_X = 56;
const TOP_Y = 780;
const LINE_HEIGHT = 14;

function normalizePdfText(value: string) {
  return value
    .replace(/₹/g, "INR ")
    .replace(/[\u2013\u2014]/g, "-")
    .replace(/[“”]/g, '"')
    .replace(/[‘’]/g, "'")
    .replace(/•/g, "-")
    .replace(/\u00a0/g, " ")
    .replace(/×/g, "x");
}

function safeText(value: unknown, fallback = "-") {
  if (typeof value !== "string") return normalizePdfText(fallback);

  const text = value.trim() || fallback;

  return normalizePdfText(text);
}

function cleanFileName(value: string) {
  return (
    value
      .replace(/[^a-z0-9]+/gi, "-")
      .replace(/^-|-$/g, "")
      .toLowerCase() || "repayment-notice"
  );
}

function wrapText(text: string, font: PDFFont, fontSize: number, maxWidth: number) {
  const words = text.split(" ");
  const lines: string[] = [];
  let currentLine = "";

  words.forEach((word) => {
    const testLine = currentLine ? `${currentLine} ${word}` : word;
    const width = font.widthOfTextAtSize(testLine, fontSize);

    if (width <= maxWidth) {
      currentLine = testLine;
    } else {
      if (currentLine) lines.push(currentLine);
      currentLine = word;
    }
  });

  if (currentLine) lines.push(currentLine);

  return lines;
}

function addNewNoticePage(pdfDoc: PDFDocument) {
  const page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);

  page.drawRectangle({
    x: 0,
    y: 0,
    width: PAGE_WIDTH,
    height: PAGE_HEIGHT,
    color: rgb(0.98, 0.99, 1),
  });

  page.drawRectangle({
    x: 0,
    y: PAGE_HEIGHT - 8,
    width: PAGE_WIDTH,
    height: 8,
    color: rgb(0.1, 0.32, 0.78),
  });

  return page;
}

function drawFooter(page: PDFPage, regularFont: PDFFont, pageNumber: number) {
  page.drawText("Generated by VENTIQ", {
    x: MARGIN_X,
    y: 34,
    size: 8,
    font: regularFont,
    color: rgb(0.38, 0.45, 0.55),
  });

  page.drawText(`Page ${pageNumber}`, {
    x: PAGE_WIDTH - MARGIN_X - 36,
    y: 34,
    size: 8,
    font: regularFont,
    color: rgb(0.38, 0.45, 0.55),
  });
}

function drawNotice(
  pdfDoc: PDFDocument,
  notice: NoticePayload,
  fonts: {
    regular: PDFFont;
    bold: PDFFont;
  },
  pageNumber: number
) {
  const page = addNewNoticePage(pdfDoc);
  let cursorY = TOP_Y;

  page.drawText("VENTIQ", {
    x: MARGIN_X,
    y: cursorY,
    size: 14,
    font: fonts.bold,
    color: rgb(0.1, 0.32, 0.78),
  });

  page.drawText("Repayment Notice", {
    x: MARGIN_X,
    y: cursorY - 34,
    size: 24,
    font: fonts.bold,
    color: rgb(0.06, 0.09, 0.16),
  });

  page.drawText(safeText(notice.companyName, "Portfolio Company"), {
    x: MARGIN_X,
    y: cursorY - 60,
    size: 11,
    font: fonts.bold,
    color: rgb(0.18, 0.24, 0.34),
  });

  page.drawText(`Due Date: ${safeText(notice.dueDate, "-")}`, {
    x: PAGE_WIDTH - MARGIN_X - 140,
    y: cursorY - 60,
    size: 10,
    font: fonts.bold,
    color: rgb(0.1, 0.32, 0.78),
  });

  cursorY -= 100;

  page.drawLine({
    start: { x: MARGIN_X, y: cursorY },
    end: { x: PAGE_WIDTH - MARGIN_X, y: cursorY },
    thickness: 1,
    color: rgb(0.8, 0.84, 0.9),
  });

  cursorY -= 28;

  const paragraphs = safeText(notice.noticeText, "").split("\n");

  paragraphs.forEach((paragraph) => {
    if (cursorY < 72) return;

    if (!paragraph.trim()) {
      cursorY -= 10;
      return;
    }

    const isSubject = paragraph.toLowerCase().startsWith("subject:");
    const isLabelLine =
      paragraph.includes(":") &&
      paragraph.length < 90 &&
      !paragraph.toLowerCase().startsWith("dear");

    const font = isSubject || isLabelLine ? fonts.bold : fonts.regular;
    const fontSize = isSubject ? 11 : 10.2;

    const wrappedLines = wrapText(
      paragraph,
      font,
      fontSize,
      PAGE_WIDTH - MARGIN_X * 2
    );

    wrappedLines.forEach((line) => {
      if (cursorY < 72) return;

      page.drawText(line, {
        x: MARGIN_X,
        y: cursorY,
        size: fontSize,
        font,
        color: isSubject ? rgb(0.1, 0.32, 0.78) : rgb(0.15, 0.2, 0.28),
      });

      cursorY -= LINE_HEIGHT;
    });

    cursorY -= 4;
  });

  drawFooter(page, fonts.regular, pageNumber);
}

export async function POST(request: Request) {
  try {
    const body = (await request.json()) as PdfRequestBody;

    const notices = Array.isArray(body.notices)
      ? body.notices
          .map((notice) => ({
            title: safeText(notice.title, "Repayment Notice"),
            companyName: safeText(notice.companyName, "Portfolio Company"),
            dueDate: safeText(notice.dueDate, "-"),
            noticeText: safeText(notice.noticeText, ""),
          }))
          .filter((notice) => notice.noticeText)
      : [];

    if (notices.length === 0) {
      return NextResponse.json(
        { error: "At least one notice is required." },
        { status: 400 }
      );
    }

    const pdfDoc = await PDFDocument.create();

    const regular = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    notices.forEach((notice, index) => {
      drawNotice(pdfDoc, notice, { regular, bold }, index + 1);
    });

    const pdfBytes = await pdfDoc.save();

    const fileName = `${cleanFileName(
      safeText(body.fileName, "repayment-notices")
    )}.pdf`;

    return new Response(Buffer.from(pdfBytes), {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${fileName}"`,
        "Content-Length": String(pdfBytes.length),
      },
    });
  } catch (error) {
    const errorMessage =
      error instanceof Error ? error.message : "Unknown PDF generation error.";

    return NextResponse.json({ error: errorMessage }, { status: 500 });
  }
}