import type { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: [
        "/",
        "/product-overview",
        "/security",
        "/faq",
        "/privacy",
        "/terms",
      ],
      disallow: [
        "/api/",
        "/admin/",
        "/auth/",
        "/workspace",
        "/site-lock",
        "/migration/",
        "/fund-onboarding",
        "/capital-call",
        "/capital-call-allocation",
        "/distribution-waterfall",
        "/document-engine",
        "/document-studio",
        "/investor-portal",
        "/investor-import",
        "/managing-partner-ai",
        "/finance-head-ai",
        "/finance",
        "/investment-team-ai",
        "/compliance-ai",
        "/fundraising-ai",
        "/portfolio-intelligence",
        "/bank-reconciliation",
        "/repayment-notice",
        "/debt-lms",
        "/data-room",
        "/knowledge-hub",
        "/activity-engine",
        "/database-test",
        "/founder/",
        "/demo",
      ],
    },
    sitemap: "https://useventiq.com/sitemap.xml",
    host: "https://useventiq.com",
  };
}