"use client";

import { useEffect, useRef, useState } from "react";
import html2canvas from "html2canvas";
import { jsPDF } from "jspdf";
import { isSupabaseConfigured, supabase } from "../../lib/supabaseClient";

type ApprovedCapitalCall = {
  id: string;
  fund_id: string | null;
  call_name: string | null;
  call_date: string | null;
  due_date: string | null;
  call_amount: number | null;
  status: string | null;
  funds: { name: string } | { name: string }[] | null;
};

type ApprovedDistribution = {
  id: string;
  fund_id: string | null;
  distribution_name: string | null;
  distribution_date: string | null;
  payment_date: string | null;
  distribution_amount: number | null;
  status: string | null;
  funds: { name: string } | { name: string }[] | null;
};

type CapitalCallInvestorRow = {
  id: string;
  investor_id: string | null;
  commitment_id: string | null;
  allocation_amount: number | null;
  call_amount: number | null;
  allocation_percentage: number | null;
  status: string | null;
  investors:
    | {
        name: string;
        email: string | null;
        investor_type: string | null;
      }
    | {
        name: string;
        email: string | null;
        investor_type: string | null;
      }[]
    | null;
};

type DistributionInvestorRow = {
  id: string;
  investor_id: string | null;
  commitment_id: string | null;
  allocation_amount: number | null;
  distribution_amount: number | null;
  allocation_percentage: number | null;
  status: string | null;
  investors:
    | {
        name: string;
        email: string | null;
        investor_type: string | null;
      }
    | {
        name: string;
        email: string | null;
        investor_type: string | null;
      }[]
    | null;
};

type InvestorDocument = {
  id: string;
  document_type: string;
  document_name: string;
  investor_name: string | null;
  investor_email: string | null;
  fund_name: string | null;
  amount: number | null;
  status: string | null;
  email_status: string | null;
  portal_status: string | null;
  storage_path: string | null;
storage_url: string | null;
  generated_at: string | null;
};

function toCr(value: number | null | undefined) {
  return Number(value || 0) / 10000000;
}

function formatCr(value: number) {
  return `₹${value.toFixed(2)} Cr`;
}

function formatDate(value: string | null | undefined) {
  if (!value) return "-";

  return new Date(value).toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

function getFundName(value: { name: string } | { name: string }[] | null) {
  if (Array.isArray(value)) return value[0]?.name ?? "Unknown Fund";
  return value?.name ?? "Unknown Fund";
}

function getInvestor(
  value:
    | {
        name: string;
        email: string | null;
        investor_type: string | null;
      }
    | {
        name: string;
        email: string | null;
        investor_type: string | null;
      }[]
    | null
) {
  if (Array.isArray(value)) return value[0] ?? null;
  return value ?? null;
}

function getDocumentTitle(documentRecord: InvestorDocument) {
  if (documentRecord.document_type === "Capital Call Notice") {
    return "Capital Call Notice";
  }

  if (documentRecord.document_type === "Distribution Notice") {
    return "Distribution Notice";
  }

  return "Investor Document";
}

function getDocumentAmountLabel(documentRecord: InvestorDocument) {
  if (documentRecord.document_type === "Capital Call Notice") {
    return "Capital Call Amount";
  }

  if (documentRecord.document_type === "Distribution Notice") {
    return "Distribution Amount";
  }

  return "Amount";
}

function getDocumentBody(documentRecord: InvestorDocument) {
  if (documentRecord.document_type === "Capital Call Notice") {
    return "This notice is being issued to inform the investor of a capital call obligation in respect of their commitment to the fund. The investor is requested to arrange payment of the capital call amount as per the fund documents and instructions issued by the investment manager.";
  }

  if (documentRecord.document_type === "Distribution Notice") {
    return "This notice is being issued to inform the investor of a distribution payable in respect of their investment in the fund. The distribution amount has been calculated based on the approved distribution waterfall and investor allocation records.";
  }

  return "This document has been generated by VENTIQ based on approved fund workflow data.";
}

function getDocumentFooter(documentRecord: InvestorDocument) {
  if (documentRecord.document_type === "Capital Call Notice") {
    return "This is a system-generated capital call notice prepared by VENTIQ for review before dispatch.";
  }

  if (documentRecord.document_type === "Distribution Notice") {
    return "This is a system-generated distribution notice prepared by VENTIQ for review before dispatch.";
  }

  return "This is a system-generated investor document prepared by VENTIQ.";
}
export default function DocumentEnginePage() {
  const [capitalCalls, setCapitalCalls] = useState<ApprovedCapitalCall[]>([]);
  const [distributions, setDistributions] = useState<ApprovedDistribution[]>(
    []
  );
  const [documents, setDocuments] = useState<InvestorDocument[]>([]);
  const [selectedCapitalCallId, setSelectedCapitalCallId] = useState("");
  const [selectedDistributionId, setSelectedDistributionId] = useState("");
  const [loading, setLoading] = useState(true);
  const [generatingCapitalCallId, setGeneratingCapitalCallId] = useState("");
  const [generatingDistributionId, setGeneratingDistributionId] = useState("");
  const [deletingDocumentId, setDeletingDocumentId] = useState("");
  const [selectedPreviewDocument, setSelectedPreviewDocument] =
  useState<InvestorDocument | null>(null);
const [generatingPdfId, setGeneratingPdfId] = useState("");
const [uploadingPdfId, setUploadingPdfId] = useState("");
const [emailActionId, setEmailActionId] = useState("");
const [bulkEmailAction, setBulkEmailAction] = useState("");
const [storingAllPdfs, setStoringAllPdfs] = useState(false);
const [bulkStoreProgress, setBulkStoreProgress] = useState("");
const previewDocumentRef = useRef<HTMLDivElement | null>(null);
const [message, setMessage] = useState("");
  const [errorMessage, setErrorMessage] = useState("");

  useEffect(() => {
    loadDocumentEngine();
  }, []);

  async function loadDocumentEngine() {
    if (!isSupabaseConfigured || !supabase) {
      setErrorMessage("Supabase is not configured. Please check .env.local.");
      setLoading(false);
      return;
    }

    setLoading(true);
    setErrorMessage("");

    const { data: callData, error: callError } = await supabase
      .from("capital_calls")
      .select(
        "id, fund_id, call_name, call_date, due_date, call_amount, status, funds(name)"
      )
      .eq("status", "approved")
      .order("created_at", { ascending: false })
      .limit(10);

    if (callError) {
      setErrorMessage(callError.message);
      setLoading(false);
      return;
    }

    const { data: distributionData, error: distributionError } = await supabase
      .from("distributions")
      .select(
        "id, fund_id, distribution_name, distribution_date, payment_date, distribution_amount, status, funds(name)"
      )
      .eq("status", "approved")
      .order("created_at", { ascending: false })
      .limit(10);

    if (distributionError) {
      setErrorMessage(distributionError.message);
      setLoading(false);
      return;
    }

    const { data: documentData, error: documentError } = await supabase
      .from("investor_documents")
      .select(
        "id, document_type, document_name, investor_name, investor_email, fund_name, amount, status, email_status, portal_status, storage_path, storage_url, generated_at"
      )
      .order("generated_at", { ascending: false })
      .limit(20);

    if (documentError) {
      setErrorMessage(documentError.message);
      setLoading(false);
      return;
    }

    const approvedCalls =
      (callData as unknown as ApprovedCapitalCall[]) ?? [];
    const approvedDistributions =
      (distributionData as unknown as ApprovedDistribution[]) ?? [];

    setCapitalCalls(approvedCalls);
    setDistributions(approvedDistributions);
    setDocuments((documentData as unknown as InvestorDocument[]) ?? []);

    if (approvedCalls[0]) {
      setSelectedCapitalCallId(approvedCalls[0].id);
    }

    if (approvedDistributions[0]) {
      setSelectedDistributionId(approvedDistributions[0].id);
    }

    setLoading(false);
  }

  async function loadDocumentsOnly() {
    if (!supabase) return;

    const { data, error } = await supabase
      .from("investor_documents")
      .select(
        "id, document_type, document_name, investor_name, investor_email, fund_name, amount, status, email_status, portal_status, storage_path, storage_url, generated_at"
      )
      .order("generated_at", { ascending: false })
      .limit(20);

    if (!error) {
      setDocuments((data as unknown as InvestorDocument[]) ?? []);
    }
  }

  async function handleDeleteInvestorDocument(documentRecord: InvestorDocument) {
    if (!supabase) {
      setMessage("Supabase is not configured.");
      return;
    }

    const confirmed = window.confirm(
      `Delete this generated document?\n\n${documentRecord.document_name}`
    );

    if (!confirmed) return;

    setDeletingDocumentId(documentRecord.id);
    setMessage("");

    const { error } = await supabase
      .from("investor_documents")
      .delete()
      .eq("id", documentRecord.id);

    if (error) {
      setMessage(`Could not delete document: ${error.message}`);
      setDeletingDocumentId("");
      return;
    }

    if (selectedPreviewDocument?.id === documentRecord.id) {
      setSelectedPreviewDocument(null);
    }

    await loadDocumentsOnly();

    setMessage("Investor document deleted successfully.");
    setDeletingDocumentId("");
  }
  async function updateInvestorDocumentEmailStatus(
  documentRecord: InvestorDocument,
  nextStatus: string
) {
  if (!supabase) {
    setMessage("Supabase is not configured.");
    return;
  }

  setEmailActionId(documentRecord.id);
  setMessage("");

  try {
    const { error } = await supabase
      .from("investor_documents")
      .update({
        email_status: nextStatus,
      })
      .eq("id", documentRecord.id);

    if (error) {
      throw error;
    }

    if (selectedPreviewDocument?.id === documentRecord.id) {
      setSelectedPreviewDocument({
        ...selectedPreviewDocument,
        email_status: nextStatus,
      });
    }

    await loadDocumentsOnly();

    setMessage(
      `${documentRecord.document_name} email status updated to ${nextStatus}.`
    );
  } catch (error) {
    setMessage(
      `Could not update email status: ${
        error instanceof Error ? error.message : "Unknown error"
      }`
    );
  }

  setEmailActionId("");
}

async function handleQueueInvestorDocumentEmail(
  documentRecord: InvestorDocument
) {
  if (!documentRecord.storage_url) {
    setMessage("Please store the PDF before queuing email.");
    return;
  }

  await updateInvestorDocumentEmailStatus(documentRecord, "queued");
}

async function handleMarkInvestorDocumentEmailSent(
  documentRecord: InvestorDocument
) {
  if (!documentRecord.storage_url) {
    setMessage("Please store the PDF before marking email as sent.");
    return;
  }

  await updateInvestorDocumentEmailStatus(documentRecord, "sent");
}

async function handleQueueAllStoredEmails() {
  if (!supabase) {
    setMessage("Supabase is not configured.");
    return;
  }

  const queueableDocuments = documents.filter(
    (documentRecord) =>
      documentRecord.storage_url &&
      documentRecord.email_status !== "queued" &&
      documentRecord.email_status !== "sent"
  );

  if (queueableDocuments.length === 0) {
    setMessage("No stored documents are pending for email queue.");
    return;
  }

  const confirmed = window.confirm(
    `Queue emails for ${queueableDocuments.length} stored investor documents?`
  );

  if (!confirmed) return;

  setBulkEmailAction("queue");
  setMessage("");

  try {
    const documentIds = queueableDocuments.map(
      (documentRecord) => documentRecord.id
    );

    const { error } = await supabase
      .from("investor_documents")
      .update({
        email_status: "queued",
      })
      .in("id", documentIds);

    if (error) {
      throw error;
    }

    await loadDocumentsOnly();

    setMessage(`${queueableDocuments.length} investor emails queued.`);
  } catch (error) {
    setMessage(
      `Could not queue emails: ${
        error instanceof Error ? error.message : "Unknown error"
      }`
    );
  }

  setBulkEmailAction("");
}

async function handleMarkAllQueuedEmailsSent() {
  if (!supabase) {
    setMessage("Supabase is not configured.");
    return;
  }

  const queuedDocuments = documents.filter(
    (documentRecord) => documentRecord.email_status === "queued"
  );

  if (queuedDocuments.length === 0) {
    setMessage("No queued emails found.");
    return;
  }

  const confirmed = window.confirm(
    `Mark ${queuedDocuments.length} queued investor emails as sent?`
  );

  if (!confirmed) return;

  setBulkEmailAction("sent");
  setMessage("");

  try {
    const documentIds = queuedDocuments.map(
      (documentRecord) => documentRecord.id
    );

    const { error } = await supabase
      .from("investor_documents")
      .update({
        email_status: "sent",
      })
      .in("id", documentIds);

    if (error) {
      throw error;
    }

    await loadDocumentsOnly();

    setMessage(`${queuedDocuments.length} investor emails marked as sent.`);
  } catch (error) {
    setMessage(
      `Could not mark emails as sent: ${
        error instanceof Error ? error.message : "Unknown error"
      }`
    );
  }

  setBulkEmailAction("");
}

  function handlePreviewInvestorDocument(documentRecord: InvestorDocument) {
    setSelectedPreviewDocument(documentRecord);
    setMessage(`Preview opened for "${documentRecord.document_name}".`);

    setTimeout(() => {
      window.document.getElementById("document-preview")?.scrollIntoView({
        behavior: "smooth",
        block: "start",
      });
    }, 100);
  }
  function getSafeFileName(value: string) {
  return value
    .replace(/[^a-z0-9]/gi, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .toLowerCase();
}

async function buildPdfForSelectedDocument() {
  if (!selectedPreviewDocument) {
    throw new Error("Please preview a document before generating PDF.");
  }

  if (!previewDocumentRef.current) {
    throw new Error("PDF preview is not ready yet.");
  }

  const canvas = await html2canvas(previewDocumentRef.current, {
    scale: 2,
    backgroundColor: "#f8fafc",
    useCORS: true,
  });

  const imageData = canvas.toDataURL("image/png");

  const pdf = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  const margin = 8;
  const pdfWidth = pageWidth - margin * 2;
  const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

  let heightLeft = pdfHeight;
  let position = margin;

  pdf.addImage(imageData, "PNG", margin, position, pdfWidth, pdfHeight);
  heightLeft -= pageHeight - margin * 2;

  while (heightLeft > 0) {
    pdf.addPage();
    position = margin - (pdfHeight - heightLeft);
    pdf.addImage(imageData, "PNG", margin, position, pdfWidth, pdfHeight);
    heightLeft -= pageHeight - margin * 2;
  }

  const fileName = `${getSafeFileName(
    selectedPreviewDocument.document_name
  )}.pdf`;

  const blob = pdf.output("blob");

  return {
    pdf,
    blob,
    fileName,
  };
}

async function handleDownloadPdf() {
  if (!selectedPreviewDocument) {
    setMessage("Please preview a document before downloading PDF.");
    return;
  }

  setGeneratingPdfId(selectedPreviewDocument.id);
  setMessage("");

  try {
    const { pdf, fileName } = await buildPdfForSelectedDocument();

    pdf.save(fileName);

    setMessage(`PDF downloaded: ${fileName}`);
  } catch (error) {
    setMessage(
      `Could not download PDF: ${
        error instanceof Error ? error.message : "Unknown error"
      }`
    );
  }

  setGeneratingPdfId("");
}

function buildPdfBlobFromDocumentRecord(documentRecord: InvestorDocument) {
  const pdf = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 16;
  const usableWidth = pageWidth - margin * 2;

  const title = getDocumentTitle(documentRecord);
  const amountLabel = getDocumentAmountLabel(documentRecord);
  const body = getDocumentBody(documentRecord);
  const footer = getDocumentFooter(documentRecord);

  let y = 18;

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(12);
  pdf.setTextColor(37, 99, 235);
  pdf.text("VENTIQ", margin, y);

  y += 12;

  pdf.setTextColor(15, 23, 42);
  pdf.setFontSize(24);
  pdf.text(title, margin, y);

  y += 12;

  pdf.setLineWidth(0.4);
  pdf.line(margin, y, pageWidth - margin, y);

  y += 16;

  pdf.setFontSize(10);
  pdf.setFont("helvetica", "bold");
  pdf.text("Generated Date", pageWidth - margin - 38, 18);
  pdf.setFont("helvetica", "normal");
  pdf.text(formatDate(documentRecord.generated_at), pageWidth - margin - 38, 24);

  pdf.setFont("helvetica", "bold");
  pdf.text("Status", pageWidth - margin - 38, 34);
  pdf.setFont("helvetica", "normal");
  pdf.text(documentRecord.status ?? "generated", pageWidth - margin - 38, 40);

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(12);
  pdf.text("Investor", margin, y);
  pdf.text("Fund", margin + usableWidth / 2, y);

  y += 7;

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(11);
  pdf.text(documentRecord.investor_name ?? "-", margin, y);
  pdf.text(documentRecord.fund_name ?? "-", margin + usableWidth / 2, y);

  y += 6;

  pdf.setFontSize(10);
  pdf.text(documentRecord.investor_email ?? "-", margin, y);
  pdf.text("Investor Reporting Document", margin + usableWidth / 2, y);

  y += 18;

  const rows = [
    ["Document Name", documentRecord.document_name],
    [amountLabel, formatCr(toCr(documentRecord.amount))],
    ["Portal Status", documentRecord.portal_status ?? "available"],
    ["Email Status", documentRecord.email_status ?? "not_sent"],
  ];

  rows.forEach(([label, value]) => {
    pdf.setDrawColor(203, 213, 225);
    pdf.rect(margin, y, usableWidth, 11);

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(10);
    pdf.setTextColor(100, 116, 139);
    pdf.text(label, margin + 4, y + 7);

    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(15, 23, 42);
    const wrappedValue = pdf.splitTextToSize(value, usableWidth / 2 - 8);
    pdf.text(wrappedValue, margin + usableWidth / 2, y + 7);

    y += 11;
  });

  y += 16;

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(11);
  pdf.setTextColor(15, 23, 42);

  const letterText = [
    `Dear ${documentRecord.investor_name ?? "Investor"},`,
    "",
    body,
    "",
    `The amount applicable to your account is ${formatCr(
      toCr(documentRecord.amount)
    )}. Please refer to the final PDF notice and fund communication for the detailed payment or distribution instructions.`,
    "",
    "This document will be made available in the investor reporting portal and may be dispatched by email once reviewed and approved by the fund operations team.",
    "",
    "Regards,",
    "VENTIQ Document Engine",
  ].join("\n");

  const wrappedText = pdf.splitTextToSize(letterText, usableWidth);
  pdf.text(wrappedText, margin, y);

  y += wrappedText.length * 6 + 14;

  pdf.setDrawColor(203, 213, 225);
  pdf.line(margin, 280, pageWidth - margin, 280);

  pdf.setFontSize(9);
  pdf.setTextColor(100, 116, 139);
  pdf.text(footer, margin, 286);
  pdf.text("Generated by VENTIQ", pageWidth - margin - 34, 286);

  const fileName = `${getSafeFileName(documentRecord.document_name)}.pdf`;
  const blob = pdf.output("blob");

  return {
    blob,
    fileName,
  };
}
async function handleStorePdfInSupabase() {
  if (!supabase) {
    setMessage("Supabase is not configured.");
    return;
  }

  if (!selectedPreviewDocument) {
    setMessage("Please preview a document before storing PDF.");
    return;
  }

  setUploadingPdfId(selectedPreviewDocument.id);
  setMessage("");

  try {
    const { blob, fileName } = await buildPdfForSelectedDocument();

    const storagePath = `${selectedPreviewDocument.id}/${fileName}`;

    const { error: uploadError } = await supabase.storage
      .from("investor-documents")
      .upload(storagePath, blob, {
        contentType: "application/pdf",
        upsert: true,
        cacheControl: "3600",
      });

    if (uploadError) {
      throw uploadError;
    }

    const { data: publicUrlData } = supabase.storage
      .from("investor-documents")
      .getPublicUrl(storagePath);

    const publicUrl = publicUrlData.publicUrl;

    const { error: updateError } = await supabase
      .from("investor_documents")
      .update({
        storage_path: storagePath,
        storage_url: publicUrl,
        status: "stored",
        portal_status: "available",
      })
      .eq("id", selectedPreviewDocument.id);

    if (updateError) {
      throw updateError;
    }

    const updatedDocument = {
      ...selectedPreviewDocument,
      storage_path: storagePath,
      storage_url: publicUrl,
      status: "stored",
      portal_status: "available",
    };

    setSelectedPreviewDocument(updatedDocument);

    await loadDocumentsOnly();

    setMessage(`PDF stored in Supabase Storage: ${fileName}`);
  } catch (error) {
    setMessage(
      `Could not store PDF: ${
        error instanceof Error ? error.message : "Unknown error"
      }`
    );
  }

  setUploadingPdfId("");
}
async function handleStoreAllPdfsInSupabase() {
  if (!supabase) {
    setMessage("Supabase is not configured.");
    return;
  }

  const unstoredDocuments = documents.filter(
    (documentRecord) => !documentRecord.storage_url
  );

  if (unstoredDocuments.length === 0) {
    setMessage("All generated documents are already stored in the portal.");
    return;
  }

  const confirmed = window.confirm(
    `Store PDFs for ${unstoredDocuments.length} unstored investor documents?`
  );

  if (!confirmed) return;

  setStoringAllPdfs(true);
  setMessage("");
  setBulkStoreProgress(`Starting bulk PDF storage for ${unstoredDocuments.length} documents...`);

  let storedCount = 0;
  let failedCount = 0;

  for (const documentRecord of unstoredDocuments) {
    try {
      setBulkStoreProgress(
        `Storing ${storedCount + failedCount + 1} of ${
          unstoredDocuments.length
        }: ${documentRecord.document_name}`
      );

      const { blob, fileName } = buildPdfBlobFromDocumentRecord(documentRecord);

      const storagePath = `${documentRecord.id}/${fileName}`;

      const { error: uploadError } = await supabase.storage
        .from("investor-documents")
        .upload(storagePath, blob, {
          contentType: "application/pdf",
          upsert: true,
          cacheControl: "3600",
        });

      if (uploadError) {
        throw uploadError;
      }

      const { data: publicUrlData } = supabase.storage
        .from("investor-documents")
        .getPublicUrl(storagePath);

      const publicUrl = publicUrlData.publicUrl;

      const { error: updateError } = await supabase
        .from("investor_documents")
        .update({
          storage_path: storagePath,
          storage_url: publicUrl,
          status: "stored",
          portal_status: "available",
        })
        .eq("id", documentRecord.id);

      if (updateError) {
        throw updateError;
      }

      storedCount += 1;
    } catch (error) {
      failedCount += 1;
      console.error("Bulk PDF store failed:", error);
    }
  }

  await loadDocumentsOnly();

  setBulkStoreProgress("");
  setMessage(
    `Bulk PDF storage completed. ${storedCount} documents stored. ${failedCount} failed.`
  );
  setStoringAllPdfs(false);
}

  async function generateCapitalCallDocuments() {
    if (!supabase) {
      setMessage("Supabase is not configured.");
      return;
    }

    const selectedCall = capitalCalls.find(
      (call) => call.id === selectedCapitalCallId
    );

    if (!selectedCall) {
      setMessage("Please select an approved capital call.");
      return;
    }

    setGeneratingCapitalCallId(selectedCall.id);
    setMessage("");

    const { data, error } = await supabase
      .from("capital_call_investors")
      .select(
        "id, investor_id, commitment_id, allocation_amount, call_amount, allocation_percentage, status, investors(name, email, investor_type)"
      )
      .eq("capital_call_id", selectedCall.id)
      .eq("status", "approved");

    if (error) {
      setMessage(`Could not read approved LP allocations: ${error.message}`);
      setGeneratingCapitalCallId("");
      return;
    }

    const rows = (data as unknown as CapitalCallInvestorRow[]) ?? [];

    if (rows.length === 0) {
      setMessage("No approved investor rows found for this capital call.");
      setGeneratingCapitalCallId("");
      return;
    }

    const fundName = getFundName(selectedCall.funds);

    const { data: existingDocuments, error: existingError } = await supabase
      .from("investor_documents")
      .select("investor_id")
      .eq("capital_call_id", selectedCall.id)
      .eq("document_type", "Capital Call Notice");

    if (existingError) {
      setMessage(`Could not check existing documents: ${existingError.message}`);
      setGeneratingCapitalCallId("");
      return;
    }

    const existingInvestorIds = new Set(
      ((existingDocuments as { investor_id: string | null }[]) ?? [])
        .map((item) => item.investor_id)
        .filter((id): id is string => Boolean(id))
    );

    const newRows = rows.filter((row) => {
      if (!row.investor_id) return true;
      return !existingInvestorIds.has(row.investor_id);
    });

    if (newRows.length === 0) {
      setMessage(
        `Capital call notices already exist for all approved investors in ${fundName}.`
      );
      setGeneratingCapitalCallId("");
      return;
    }

    const payload = newRows.map((row) => {
      const investor = getInvestor(row.investors);

      return {
        investor_id: row.investor_id,
        fund_id: selectedCall.fund_id,
        capital_call_id: selectedCall.id,
        distribution_id: null,
        document_type: "Capital Call Notice",
        document_name: `${
          selectedCall.call_name ?? "Capital Call"
        } - ${investor?.name ?? "Investor"}`,
        investor_name: investor?.name ?? "Unknown Investor",
        investor_email: investor?.email ?? null,
        fund_name: fundName,
        amount: row.allocation_amount ?? row.call_amount ?? 0,
        status: "generated",
        email_status: "not_sent",
        portal_status: "available",
        generated_by: "VENTIQ Document Engine",
      };
    });

    const { error: insertError } = await supabase
      .from("investor_documents")
      .insert(payload);

    if (insertError) {
      setMessage(`Could not generate documents: ${insertError.message}`);
      setGeneratingCapitalCallId("");
      return;
    }

    await loadDocumentsOnly();

    setMessage(
      `${newRows.length} new capital call notice records generated for ${fundName}. ${
        rows.length - newRows.length
      } duplicate records skipped.`
    );
    setGeneratingCapitalCallId("");
  }

  async function generateDistributionDocuments() {
    if (!supabase) {
      setMessage("Supabase is not configured.");
      return;
    }

    const selectedDistribution = distributions.find(
      (distribution) => distribution.id === selectedDistributionId
    );

    if (!selectedDistribution) {
      setMessage("Please select an approved distribution.");
      return;
    }

    setGeneratingDistributionId(selectedDistribution.id);
    setMessage("");

    const { data, error } = await supabase
      .from("distribution_investors")
      .select(
        "id, investor_id, commitment_id, allocation_amount, distribution_amount, allocation_percentage, status, investors(name, email, investor_type)"
      )
      .eq("distribution_id", selectedDistribution.id)
      .eq("status", "approved");

    if (error) {
      setMessage(`Could not read approved LP allocations: ${error.message}`);
      setGeneratingDistributionId("");
      return;
    }

    const rows = (data as unknown as DistributionInvestorRow[]) ?? [];

    if (rows.length === 0) {
      setMessage("No approved investor rows found for this distribution.");
      setGeneratingDistributionId("");
      return;
    }

    const fundName = getFundName(selectedDistribution.funds);

    const { data: existingDocuments, error: existingError } = await supabase
      .from("investor_documents")
      .select("investor_id")
      .eq("distribution_id", selectedDistribution.id)
      .eq("document_type", "Distribution Notice");

    if (existingError) {
      setMessage(`Could not check existing documents: ${existingError.message}`);
      setGeneratingDistributionId("");
      return;
    }

    const existingInvestorIds = new Set(
      ((existingDocuments as { investor_id: string | null }[]) ?? [])
        .map((item) => item.investor_id)
        .filter((id): id is string => Boolean(id))
    );

    const newRows = rows.filter((row) => {
      if (!row.investor_id) return true;
      return !existingInvestorIds.has(row.investor_id);
    });

    if (newRows.length === 0) {
      setMessage(
        `Distribution notices already exist for all approved investors in ${fundName}.`
      );
      setGeneratingDistributionId("");
      return;
    }

    const payload = newRows.map((row) => {
      const investor = getInvestor(row.investors);

      return {
        investor_id: row.investor_id,
        fund_id: selectedDistribution.fund_id,
        capital_call_id: null,
        distribution_id: selectedDistribution.id,
        document_type: "Distribution Notice",
        document_name: `${
          selectedDistribution.distribution_name ?? "Distribution"
        } - ${investor?.name ?? "Investor"}`,
        investor_name: investor?.name ?? "Unknown Investor",
        investor_email: investor?.email ?? null,
        fund_name: fundName,
        amount: row.allocation_amount ?? row.distribution_amount ?? 0,
        status: "generated",
        email_status: "not_sent",
        portal_status: "available",
        generated_by: "VENTIQ Document Engine",
      };
    });

    const { error: insertError } = await supabase
      .from("investor_documents")
      .insert(payload);

    if (insertError) {
      setMessage(`Could not generate documents: ${insertError.message}`);
      setGeneratingDistributionId("");
      return;
    }

    await loadDocumentsOnly();

    setMessage(
      `${newRows.length} new distribution notice records generated for ${fundName}. ${
        rows.length - newRows.length
      } duplicate records skipped.`
    );
    setGeneratingDistributionId("");
  }

  return (
    <main className="app-page">
      <section className="app-shell">
        <div className="app-header">
          <div>
            <p className="eyebrow">VENTIQ Reporting</p>
            <h1>Document Generation Engine</h1>
            <p>
              Generate investor-wise capital call notices, distribution notices
              and reporting documents from approved fund workflows.
            </p>
          </div>

          <a className="back-link" href="/">
            Back to Home
          </a>
        </div>

        {loading && (
          <div className="preview-card">
            <h2>Loading Document Engine...</h2>
            <p>
              VENTIQ is reading approved capital calls, distributions and
              investor document records.
            </p>
          </div>
        )}

        {!loading && errorMessage && (
          <div className="preview-card">
            <h2>Connection Issue</h2>
            <div className="explain-box">
              <strong>Error:</strong> {errorMessage}
            </div>
          </div>
        )}

        {!loading && !errorMessage && (
          <>
            <div className="impact-grid">
              <div className="impact-card">
                <h3>{capitalCalls.length}</h3>
                <p>Approved capital calls</p>
              </div>

              <div className="impact-card">
                <h3>{distributions.length}</h3>
                <p>Approved distributions</p>
              </div>

              <div className="impact-card">
                <h3>{documents.length}</h3>
                <p>Recent documents</p>
              </div>

              <div className="impact-card">
                <h3>Portal Ready</h3>
                <p>Document status</p>
              </div>
            </div>

            <div className="preview-card">
              <h2>AI Document Workflow</h2>

              <div className="explain-box">
                VENTIQ only generates investor reporting documents from approved
                workflows. Once generated, each investor document is linked to
                the investor, fund, workflow and future portal/email status.
              </div>

              {message && <div className="logic-note">{message}</div>}
            </div>

            <div className="preview-card">
              <h2>Generate Capital Call Notices</h2>

              <p className="eyebrow">
                Create investor-wise notice records from approved capital calls
              </p>

              {capitalCalls.length === 0 && (
                <div className="explain-box">
                  No approved capital calls found yet. Approve a capital call
                  first from the Capital Call module.
                </div>
              )}

              {capitalCalls.length > 0 && (
                <div className="form-card">
                  <label>Approved Capital Call</label>
                  <select
                    value={selectedCapitalCallId}
                    onChange={(event) =>
                      setSelectedCapitalCallId(event.target.value)
                    }
                  >
                    {capitalCalls.map((call) => (
                      <option key={call.id} value={call.id}>
                        {call.call_name ?? "Approved Capital Call"} —{" "}
                        {formatCr(toCr(call.call_amount))}
                      </option>
                    ))}
                  </select>

                  <div className="logic-note">
                    Selected capital call notices will be generated LP-wise and
                    marked as portal available. Email status will remain not
                    sent until the Email Dispatch Engine is connected.
                  </div>

                  <div className="action-row">
                    <button
                      type="button"
                      onClick={generateCapitalCallDocuments}
                      disabled={generatingCapitalCallId !== ""}
                    >
                      {generatingCapitalCallId
                        ? "Generating..."
                        : "Generate Capital Call Notices"}
                    </button>
                  </div>
                </div>
              )}
            </div>

            <div className="preview-card">
              <h2>Generate Distribution Notices</h2>

              <p className="eyebrow">
                Create investor-wise notice records from approved distributions
              </p>

              {distributions.length === 0 && (
                <div className="explain-box">
                  No approved distributions found yet. Approve a distribution
                  first from the Distribution Waterfall module.
                </div>
              )}

              {distributions.length > 0 && (
                <div className="form-card">
                  <label>Approved Distribution</label>
                  <select
                    value={selectedDistributionId}
                    onChange={(event) =>
                      setSelectedDistributionId(event.target.value)
                    }
                  >
                    {distributions.map((distribution) => (
                      <option key={distribution.id} value={distribution.id}>
                        {distribution.distribution_name ??
                          "Approved Distribution"}{" "}
                        — {formatCr(toCr(distribution.distribution_amount))}
                      </option>
                    ))}
                  </select>

                  <div className="logic-note">
                    Selected distribution notices will be generated LP-wise and
                    marked as portal available. Email status will remain not
                    sent until the Email Dispatch Engine is connected.
                  </div>

                  <div className="action-row">
                    <button
                      type="button"
                      onClick={generateDistributionDocuments}
                      disabled={generatingDistributionId !== ""}
                    >
                      {generatingDistributionId
                        ? "Generating..."
                        : "Generate Distribution Notices"}
                    </button>
                  </div>
                </div>
              )}
            </div>

           <div className="preview-card">
  <h2>Generated Investor Documents</h2>

  <p className="eyebrow">
    Latest investor document records from Supabase
  </p>
  <div className="action-row">
  <button
    type="button"
    onClick={handleStoreAllPdfsInSupabase}
    disabled={storingAllPdfs || documents.length === 0}
  >
    {storingAllPdfs ? "Storing All PDFs..." : "Store All PDFs to Portal"}
  </button>
  <div className="action-row">
  <button
    type="button"
    onClick={handleQueueAllStoredEmails}
    disabled={bulkEmailAction === "queue" || documents.length === 0}
  >
    {bulkEmailAction === "queue"
      ? "Queuing Emails..."
      : "Queue All Stored Emails"}
  </button>

  <button
    type="button"
    onClick={handleMarkAllQueuedEmailsSent}
    disabled={bulkEmailAction === "sent" || documents.length === 0}
  >
    {bulkEmailAction === "sent"
      ? "Marking Sent..."
      : "Mark All Queued as Sent"}
  </button>
</div>
</div>

{bulkStoreProgress && <div className="logic-note">{bulkStoreProgress}</div>}

  {documents.length === 0 && (
    <div className="explain-box">
      No investor documents generated yet.
    </div>
  )}

  {documents.length > 0 && (
    <div
      style={{
        overflowX: "auto",
        overflowY: "auto",
        maxHeight: "560px",
        border: "1px solid rgba(148, 163, 184, 0.22)",
        borderRadius: "18px",
      }}
    >
      <table
        className="investor-table"
        style={{
          minWidth: "1250px",
          width: "100%",
        }}
      >
        <thead>
          <tr>
            <th>Document</th>
            <th>Type</th>
            <th>Investor</th>
            <th>Email</th>
            <th>Fund</th>
            <th>Amount</th>
            <th>Portal</th>
            <th>Email</th>
            <th>Generated</th>
            <th>Action</th>
          </tr>
        </thead>

        <tbody>
  {documents.map((documentRecord) => (
    <tr key={documentRecord.id}>
      <td style={{ maxWidth: "260px" }}>
        <strong>{documentRecord.document_name}</strong>
      </td>

      <td>{documentRecord.document_type}</td>

      <td>{documentRecord.investor_name ?? "-"}</td>

      <td>{documentRecord.investor_email ?? "-"}</td>

      <td>{documentRecord.fund_name ?? "-"}</td>

      <td>{formatCr(toCr(documentRecord.amount))}</td>

      <td>
        <span className="small-pill">
          {documentRecord.portal_status ?? "available"}
        </span>
      </td>

      <td>
        <span className="small-pill">
          {documentRecord.email_status ?? "not_sent"}
        </span>
      </td>

      <td>{formatDate(documentRecord.generated_at)}</td>

      <td>
        <div
          style={{
            display: "flex",
            gap: "10px",
            alignItems: "center",
            flexWrap: "nowrap",
          }}
        >
          <button
            type="button"
            onClick={() => handlePreviewInvestorDocument(documentRecord)}
            style={{
              border: "1px solid rgba(96, 165, 250, 0.45)",
              background: "rgba(37, 99, 235, 0.16)",
              color: "#dbeafe",
              borderRadius: "999px",
              padding: "8px 16px",
              fontSize: "14px",
              fontWeight: 700,
              cursor: "pointer",
              whiteSpace: "nowrap",
            }}
          >
            Preview
          </button>

          {!documentRecord.storage_url && (
            <span className="small-pill">Store PDF First</span>
          )}

          {documentRecord.storage_url &&
            documentRecord.email_status !== "queued" &&
            documentRecord.email_status !== "sent" && (
              <button
                type="button"
                onClick={() => handleQueueInvestorDocumentEmail(documentRecord)}
                disabled={emailActionId === documentRecord.id}
                style={{
                  border: "1px solid rgba(251, 191, 36, 0.45)",
                  background: "rgba(120, 53, 15, 0.18)",
                  color: "#fde68a",
                  borderRadius: "999px",
                  padding: "8px 16px",
                  fontSize: "14px",
                  fontWeight: 700,
                  cursor:
                    emailActionId === documentRecord.id
                      ? "not-allowed"
                      : "pointer",
                  opacity: emailActionId === documentRecord.id ? 0.6 : 1,
                  whiteSpace: "nowrap",
                }}
              >
                {emailActionId === documentRecord.id
                  ? "Queuing..."
                  : "Queue Email"}
              </button>
            )}

          {documentRecord.storage_url &&
            documentRecord.email_status === "queued" && (
              <button
                type="button"
                onClick={() =>
                  handleMarkInvestorDocumentEmailSent(documentRecord)
                }
                disabled={emailActionId === documentRecord.id}
                style={{
                  border: "1px solid rgba(74, 222, 128, 0.45)",
                  background: "rgba(22, 101, 52, 0.18)",
                  color: "#bbf7d0",
                  borderRadius: "999px",
                  padding: "8px 16px",
                  fontSize: "14px",
                  fontWeight: 700,
                  cursor:
                    emailActionId === documentRecord.id
                      ? "not-allowed"
                      : "pointer",
                  opacity: emailActionId === documentRecord.id ? 0.6 : 1,
                  whiteSpace: "nowrap",
                }}
              >
                {emailActionId === documentRecord.id
                  ? "Updating..."
                  : "Mark Sent"}
              </button>
            )}

          {documentRecord.email_status === "sent" && (
            <span className="small-pill">Sent</span>
          )}

          <button
            type="button"
            onClick={() => handleDeleteInvestorDocument(documentRecord)}
            disabled={deletingDocumentId === documentRecord.id}
            style={{
              border: "1px solid rgba(248, 113, 113, 0.45)",
              background: "rgba(127, 29, 29, 0.18)",
              color: "#fecaca",
              borderRadius: "999px",
              padding: "8px 16px",
              fontSize: "14px",
              fontWeight: 700,
              cursor:
                deletingDocumentId === documentRecord.id
                  ? "not-allowed"
                  : "pointer",
              opacity: deletingDocumentId === documentRecord.id ? 0.6 : 1,
              whiteSpace: "nowrap",
            }}
          >
            {deletingDocumentId === documentRecord.id
              ? "Deleting..."
              : "Delete"}
          </button>
        </div>
      </td>
    </tr>
  ))}
</tbody>
      </table>
    </div>
  )}
</div>

{selectedPreviewDocument && (
  <div id="document-preview" className="preview-card">
    <h2>PDF-style Document Preview</h2>

    <p className="eyebrow">
      Review-ready notice template generated from investor document data
    </p>

    <div className="impact-grid">
      <div className="impact-card">
        <h3>{getDocumentTitle(selectedPreviewDocument)}</h3>
        <p>Document type</p>
      </div>

      <div className="impact-card">
        <h3>{selectedPreviewDocument.investor_name ?? "-"}</h3>
        <p>Investor</p>
      </div>

      <div className="impact-card">
        <h3>{formatCr(toCr(selectedPreviewDocument.amount))}</h3>
        <p>{getDocumentAmountLabel(selectedPreviewDocument)}</p>
      </div>

      <div className="impact-card">
        <h3>{selectedPreviewDocument.email_status ?? "not_sent"}</h3>
        <p>Email status</p>
      </div>
    </div>

    <div
  ref={previewDocumentRef}
      style={{
        background: "#f8fafc",
        color: "#0f172a",
        borderRadius: "18px",
        padding: "36px",
        border: "1px solid rgba(148, 163, 184, 0.35)",
        boxShadow: "0 24px 80px rgba(0, 0, 0, 0.25)",
      }}
    >
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          gap: "24px",
          borderBottom: "2px solid #0f172a",
          paddingBottom: "18px",
          marginBottom: "28px",
        }}
      >
        <div>
          <p
            style={{
              color: "#2563eb",
              fontWeight: 800,
              letterSpacing: "0.08em",
              textTransform: "uppercase",
              margin: 0,
            }}
          >
            VENTIQ
          </p>

          <h2
            style={{
              margin: "8px 0 0",
              color: "#0f172a",
              fontSize: "32px",
            }}
          >
            {getDocumentTitle(selectedPreviewDocument)}
          </h2>
        </div>

        <div style={{ textAlign: "right", fontSize: "14px" }}>
          <strong>Generated Date</strong>
          <br />
          {formatDate(selectedPreviewDocument.generated_at)}
          <br />
          <br />
          <strong>Status</strong>
          <br />
          {selectedPreviewDocument.status ?? "generated"}
        </div>
      </div>

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "1fr 1fr",
          gap: "18px",
          marginBottom: "28px",
        }}
      >
        <div
          style={{
            border: "1px solid #cbd5e1",
            borderRadius: "14px",
            padding: "18px",
            background: "#ffffff",
          }}
        >
          <p style={{ margin: "0 0 8px", color: "#64748b" }}>Investor</p>
          <strong>{selectedPreviewDocument.investor_name ?? "-"}</strong>
          <br />
          <span>{selectedPreviewDocument.investor_email ?? "-"}</span>
        </div>

        <div
          style={{
            border: "1px solid #cbd5e1",
            borderRadius: "14px",
            padding: "18px",
            background: "#ffffff",
          }}
        >
          <p style={{ margin: "0 0 8px", color: "#64748b" }}>Fund</p>
          <strong>{selectedPreviewDocument.fund_name ?? "-"}</strong>
          <br />
          <span>Investor Reporting Document</span>
        </div>
      </div>

      <div
        style={{
          border: "1px solid #cbd5e1",
          borderRadius: "14px",
          overflow: "hidden",
          marginBottom: "28px",
          background: "#ffffff",
        }}
      >
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1fr 1fr",
            borderBottom: "1px solid #e2e8f0",
          }}
        >
          <div style={{ padding: "16px", color: "#64748b" }}>
            Document Name
          </div>
          <div style={{ padding: "16px", fontWeight: 700 }}>
            {selectedPreviewDocument.document_name}
          </div>
        </div>

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1fr 1fr",
            borderBottom: "1px solid #e2e8f0",
          }}
        >
          <div style={{ padding: "16px", color: "#64748b" }}>
            {getDocumentAmountLabel(selectedPreviewDocument)}
          </div>
          <div style={{ padding: "16px", fontWeight: 700 }}>
            {formatCr(toCr(selectedPreviewDocument.amount))}
          </div>
        </div>

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1fr 1fr",
            borderBottom: "1px solid #e2e8f0",
          }}
        >
          <div style={{ padding: "16px", color: "#64748b" }}>
            Portal Status
          </div>
          <div style={{ padding: "16px", fontWeight: 700 }}>
            {selectedPreviewDocument.portal_status ?? "available"}
          </div>
          <div className="journal-row">
  <span>Storage Status</span>
  <strong>
    {selectedPreviewDocument.storage_url ? "PDF stored" : "Not stored yet"}
  </strong>
</div>
        </div>

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1fr 1fr",
          }}
        >
          <div style={{ padding: "16px", color: "#64748b" }}>
            Email Status
          </div>
          <div style={{ padding: "16px", fontWeight: 700 }}>
            {selectedPreviewDocument.email_status ?? "not_sent"}
          </div>
        </div>
      </div>

      <div
        style={{
          border: "1px solid #cbd5e1",
          borderRadius: "14px",
          padding: "22px",
          background: "#ffffff",
          lineHeight: 1.7,
          marginBottom: "28px",
        }}
      >
        <p style={{ marginTop: 0 }}>
          Dear <strong>{selectedPreviewDocument.investor_name ?? "Investor"}</strong>,
        </p>

        <p>{getDocumentBody(selectedPreviewDocument)}</p>

        <p>
          The amount applicable to your account is{" "}
          <strong>{formatCr(toCr(selectedPreviewDocument.amount))}</strong>.
          Please refer to the final PDF notice and fund communication for the
          detailed payment or distribution instructions.
        </p>

        <p>
          This document will be made available in the investor reporting portal
          and may be dispatched by email once reviewed and approved by the fund
          operations team.
        </p>

        <p style={{ marginBottom: 0 }}>
          Regards,
          <br />
          <strong>VENTIQ Document Engine</strong>
        </p>
      </div>

      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          gap: "20px",
          borderTop: "1px solid #cbd5e1",
          paddingTop: "18px",
          color: "#64748b",
          fontSize: "13px",
        }}
      >
        <span>{getDocumentFooter(selectedPreviewDocument)}</span>
        <span>Generated by VENTIQ</span>
      </div>
    </div>

   <div className="action-row" style={{ marginTop: "20px" }}>
  <button
    type="button"
    onClick={handleDownloadPdf}
    disabled={
      !selectedPreviewDocument ||
      generatingPdfId === selectedPreviewDocument.id
    }
  >
    {generatingPdfId === selectedPreviewDocument?.id
      ? "Generating PDF..."
      : "Download PDF"}
  </button>

  <button
    type="button"
    onClick={handleStorePdfInSupabase}
    disabled={
      !selectedPreviewDocument ||
      uploadingPdfId === selectedPreviewDocument.id
    }
  >
    {uploadingPdfId === selectedPreviewDocument?.id
      ? "Storing PDF..."
      : "Store PDF to Portal"}
  </button>

  {selectedPreviewDocument?.storage_url && (
    <a
      href={selectedPreviewDocument.storage_url}
      target="_blank"
      rel="noreferrer"
      style={{
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        border: "1px solid rgba(74, 222, 128, 0.45)",
        background: "rgba(22, 101, 52, 0.18)",
        color: "#bbf7d0",
        borderRadius: "999px",
        padding: "12px 18px",
        fontSize: "15px",
        fontWeight: 800,
        textDecoration: "none",
      }}
    >
      Open Stored PDF
    </a>
  )}

  {selectedPreviewDocument?.email_status !== "queued" &&
  selectedPreviewDocument?.email_status !== "sent" && (
    <button
      type="button"
      onClick={() =>
        handleQueueInvestorDocumentEmail(selectedPreviewDocument)
      }
      disabled={
        !selectedPreviewDocument.storage_url ||
        emailActionId === selectedPreviewDocument.id
      }
    >
      {emailActionId === selectedPreviewDocument.id
        ? "Queuing Email..."
        : "Queue Email"}
    </button>
  )}

{selectedPreviewDocument?.email_status === "queued" && (
  <button
    type="button"
    onClick={() =>
      handleMarkInvestorDocumentEmailSent(selectedPreviewDocument)
    }
    disabled={emailActionId === selectedPreviewDocument.id}
  >
    {emailActionId === selectedPreviewDocument.id
      ? "Updating..."
      : "Mark Email Sent"}
  </button>
)}

{selectedPreviewDocument?.email_status === "sent" && (
  <button type="button" disabled>
    Email Sent
  </button>
)}
</div>

    <div className="explain-box">
      This is now a PDF-style preview. In Phase 3.4, we will convert this
      template into an actual downloadable PDF and later store the PDF link in
      Supabase Storage.
    </div>
  </div>
)}

            <div className="preview-card">
              <h2>Next Step After Phase 3.3</h2>

              <div className="queue-grid">
                <div className="queue-item">
                  🟢 Approved workflow selected
                </div>

                <div className="queue-item">
                  🟢 Investor document records generated
                </div>

                <div className="queue-item">
                  🟢 Duplicate prevention added
                </div>

                <div className="queue-item">
                  🟢 Document preview placeholder added
                </div>

                <div className="queue-item">
                  🟢 PDF-style preview template added
                </div>

                <div className="queue-item">
                  🟡 Supabase Storage file link pending
                </div>

                <div className="queue-item">
                  🟡 Investor portal document view pending
                </div>

                <div className="queue-item">
                  🟡 Email dispatch pending
                </div>
              </div>
            </div>
          </>
        )}
      </section>
    </main>
  );
}